import type { Book, Genre } from '@/types';

export const BOOKS: Book[] = [
  {
    id: '1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    genre: 'Fiction',
    year: 2020,
    pages: 288,
    rating: 4.3,
    available: true,
    cover: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=450&fit=crop',
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices.',
    isbn: '978-0-525-55947-4',
    language: 'English',
    publisher: 'Viking'
  },
  {
    id: '2',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    genre: 'Science Fiction',
    year: 2021,
    pages: 476,
    rating: 4.7,
    available: true,
    cover: 'https://images.unsplash.com/photo-1614728263952-84ea256f9d1d?w=300&h=450&fit=crop',
    description: 'A lone astronaut must save the earth from disaster in this propulsive, gripping, and technically brilliant new science fiction adventure.',
    isbn: '978-0-593-13520-4',
    language: 'English',
    publisher: 'Ballantine Books'
  },
  {
    id: '3',
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    genre: 'Literary Fiction',
    year: 2021,
    pages: 320,
    rating: 4.1,
    available: false,
    cover: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=450&fit=crop',
    description: 'From her place in the store, Klara, an Artificial Friend with outstanding observational qualities, watches carefully the behavior of those who come in to browse.',
    isbn: '978-0-593-31817-1',
    language: 'English',
    publisher: 'Knopf'
  },
  {
    id: '4',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    genre: 'Fantasy',
    year: 2007,
    pages: 662,
    rating: 4.5,
    available: true,
    cover: 'https://images.unsplash.com/photo-1518744386442-2d48ac47a7eb?w=300&h=450&fit=crop',
    description: 'The tale of Kvothe, from his childhood in a troupe of traveling players, to years spent as a near-feral orphan in a crime-ridden city.',
    isbn: '978-0-7564-0407-9',
    language: 'English',
    publisher: 'DAW Books'
  },
  {
    id: '5',
    title: 'Educated',
    author: 'Tara Westover',
    genre: 'Memoir',
    year: 2018,
    pages: 334,
    rating: 4.6,
    available: true,
    cover: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=300&h=450&fit=crop',
    description: 'A memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.',
    isbn: '978-0-399-59050-4',
    language: 'English',
    publisher: 'Random House'
  },
  {
    id: '6',
    title: 'The House in the Cerulean Sea',
    author: 'TJ Klune',
    genre: 'Fantasy',
    year: 2020,
    pages: 394,
    rating: 4.4,
    available: false,
    cover: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=300&h=450&fit=crop',
    description: 'A magical island. A dangerous task. A burning secret. Two men found each other with all the world standing against them.',
    isbn: '978-1-250-21728-6',
    language: 'English',
    publisher: 'Tor Books'
  },
  {
    id: '7',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    genre: 'Non-Fiction',
    year: 2011,
    pages: 443,
    rating: 4.4,
    available: true,
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=450&fit=crop',
    description: 'A brief history of humankind, exploring how Homo sapiens came to dominate the earth.',
    isbn: '978-0-06-231609-7',
    language: 'English',
    publisher: 'Harper'
  },
  {
    id: '8',
    title: 'Normal People',
    author: 'Sally Rooney',
    genre: 'Fiction',
    year: 2018,
    pages: 266,
    rating: 3.9,
    available: true,
    cover: 'https://images.unsplash.com/photo-1531072901881-d644216d4bf9?w=300&h=450&fit=crop',
    description: 'Connell and Marianne grow up in the same small town in the west of Ireland. The novel follows their relationship from school to university.',
    isbn: '978-0-571-33489-5',
    language: 'English',
    publisher: 'Faber & Faber'
  },
  {
    id: '9',
    title: 'The Shadow of the Wind',
    author: 'Carlos Ruiz Zafón',
    genre: 'Mystery',
    year: 2001,
    pages: 487,
    rating: 4.5,
    available: true,
    cover: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=300&h=450&fit=crop',
    description: 'A young boy discovers a mysterious book that sets him on an adventure through the shadowy streets of post-war Barcelona.',
    isbn: '978-0-14-303490-7',
    language: 'English',
    publisher: 'Penguin'
  },
  {
    id: '10',
    title: 'Atomic Habits',
    author: 'James Clear',
    genre: 'Self-Help',
    year: 2018,
    pages: 320,
    rating: 4.8,
    available: false,
    cover: 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=300&h=450&fit=crop',
    description: 'A revolutionary system to get 1 percent better every day. The definitive guide to breaking bad behaviors and adopting good ones.',
    isbn: '978-0-7352-1129-2',
    language: 'English',
    publisher: 'Avery'
  },
  {
    id: '11',
    title: 'Dune',
    author: 'Frank Herbert',
    genre: 'Science Fiction',
    year: 1965,
    pages: 688,
    rating: 4.7,
    available: true,
    cover: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=300&h=450&fit=crop',
    description: 'Set in the distant future amidst a feudal interstellar society, Dune tells the story of young Paul Atreides as his family takes control of the desert planet Arrakis.',
    isbn: '978-0-441-17271-9',
    language: 'English',
    publisher: 'Chilton Books'
  },
  {
    id: '12',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    genre: 'Fiction',
    year: 1988,
    pages: 208,
    rating: 4.2,
    available: true,
    cover: 'https://images.unsplash.com/photo-1416795142053-a81f0af1e68e?w=300&h=450&fit=crop',
    description: 'A magical fable about following your dream. A young Andalusian shepherd journeys from his homeland in Spain to the Egyptian desert in search of a treasure.',
    isbn: '978-0-06-231500-7',
    language: 'English',
    publisher: 'HarperCollins'
  }
];

export const GENRES: Genre[] = [
  { id: 'fiction', name: 'Fiction', icon: '📖', count: 3, color: 'bg-blue-100 text-blue-800' },
  { id: 'sci-fi', name: 'Science Fiction', icon: '🚀', count: 2, color: 'bg-purple-100 text-purple-800' },
  { id: 'fantasy', name: 'Fantasy', icon: '🧙', count: 2, color: 'bg-green-100 text-green-800' },
  { id: 'non-fiction', name: 'Non-Fiction', icon: '🔬', count: 1, color: 'bg-orange-100 text-orange-800' },
  { id: 'mystery', name: 'Mystery', icon: '🔍', count: 1, color: 'bg-red-100 text-red-800' },
  { id: 'memoir', name: 'Memoir', icon: '✍️', count: 1, color: 'bg-yellow-100 text-yellow-800' },
  { id: 'self-help', name: 'Self-Help', icon: '💡', count: 1, color: 'bg-teal-100 text-teal-800' },
  { id: 'literary', name: 'Literary Fiction', icon: '🖋️', count: 1, color: 'bg-pink-100 text-pink-800' },
];

export const FEATURED_BOOKS = BOOKS.slice(0, 4);
